services:
  db:
    image: postgres:12-alpine
    container_name: bitwaredb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: bitware123
      POSTGRES_DB: bitwaredb
    volumes:
      - ./postgres:/var/lib/postgres/data

volumes:
  postgres: